### ISSUE TITLE
Provision: create a versioning file in this repo and write a MOTD

### ISSUE THREAD

**Issue by Jamie-** [pexip/rp-turn#7]
Example ansible config
```
    - name: "Set MOTD"
      template:
        src: "{{ git_root }}/platform/ansible/files/etc/motd.j2"
        dest: "/etc/motd"
        owner: root
        group: root
        mode: 0644

    - name: "Clean Ubuntu /etc/update-motd.d"
      file:
        state: absent
        path: /etc/update-motd.d/
```

Create motd which reads the version file from https://github.com/pexip/rp-turn/issues/8 and generates a MOTD which looks like:
```

#############################################

Product name : $NAME
Version      : $VERSION
Build        : $BUILD
Build Date   : $BUILD_DATE

#############################################
```
